# Default usage

dns_regru_username=test
dns_regru_password=test

# SSL certificate authentication

# dns_regru_cert_path=/path/to/cert.pem
# dns_regru_key_path=/path/to/key.pem

# Uncomment for external registrar service

# dns_regru_service_id=test